name: Cypress API Tests Pipeline
on:
  pull_request:
    branches:
      - main
jobs:
  cypress-api-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project 
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
    